### ISSUE TITLE
Can we update cloudbox_mod to install the same was community does

### ISSUE THREAD

**Issue by MollyBe** [Cloudbox/cloudbox_mod#3]
Per the community [wiki](https://github.com/Cloudbox/Community/wiki/Install)

## Install / Update Community Repo

Run the following commands:

```bash
cd ~/cloudbox; git fetch &> /dev/null; git reset --hard @{u} &> /dev/null; sudo ansible-playbook cloudbox.yml --tags community
```

This will clone the repo into `/opt/community`, symlink the folder to `~/community`, and add the necessary `vault_password_file` line to `/opt/community/ansible.cfg`.

**Comment by desimaniac** [comment]
It's just a basic template for you to build on; you can clone it and put it anywhere you want. 

As far as me including it into CB main as a tag, not used by many so want to leave CB clear from bloat.
